language: python

python:
#  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
dist: xenial
sudo: true

matrix:
  fast_finish: true

install:
  - pip install tox
  - pip install coverage
  - pip install coveralls
  - pip install .

script:
# - tox
  - coverage run --source=quantulum3 scripts/test_import_error.py
  - coverage run -a --source=quantulum3 setup.py test -s quantulum3.tests.test_setup
  - coverage run -a --source=quantulum3 setup.py test -s quantulum3.tests.test_no_classifier
  - pip install -r requirements_classifier.txt
  - coverage run -a --source=quantulum3 setup.py test -s quantulum3.tests.test_classifier

after_success:
  - coverage report
  - coveralls
