language: python

python:
#  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
dist: xenial
sudo: true

matrix:
  fast_finish: true

install:
  - pip install coverage
  - pip install coveralls

script:
  - coverage run test.py
  # Run a second time to make sure the socket was closed correctly last time
  - coverage run test.py

after_success:
  - coverage report
  - coveralls
